version: '3'

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    #    volumes:
    #      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    #    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  pg_data:
