# Generated by Django 4.2.13 on 2024-11-26 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_view",
                    models.CharField(
                        choices=[("CARDS", "Cards"), ("LIST", "List")],
                        default="LIST",
                        max_length=64,
                    ),
                ),
                (
                    "vendor_view",
                    models.CharField(
                        choices=[("CARDS", "Cards"), ("LIST", "List")],
                        default="CARDS",
                        max_length=64,
                    ),
                ),
                (
                    "order_view",
                    models.CharField(
                        choices=[("CARDS", "Cards"), ("LIST", "List")],
                        default="CARDS",
                        max_length=64,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
