# Generated by Django 4.2.13 on 2025-03-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("NON_SHAREHOLDER", "Non-shareholder"),
                    ("SHAREHOLDER", "Shareholder"),
                    ("SHAREHOLDER_RESALE", "Shareholder Resale"),
                    ("EMPLOYEE", "Employee"),
                    ("FLOWER", "FLOWER (Non-Redeemable Share)"),
                ],
                max_length=64,
                unique=True,
            ),
        ),
    ]
