# Generated by Django 4.2.13 on 2024-06-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="rank",
            field=models.PositiveSmallIntegerField(default=9999),
        ),
    ]
