# Generated by Django 4.2.6 on 2023-11-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="delivery_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Monday"),
                    ("1", "Tuesday"),
                    ("2", "Wednesday"),
                    ("3", "Thursday"),
                    ("4", "Friday"),
                    ("5", "Saturday"),
                    ("6", "Sunday"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="order_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Monday"),
                    ("1", "Tuesday"),
                    ("2", "Wednesday"),
                    ("3", "Thursday"),
                    ("4", "Friday"),
                    ("5", "Saturday"),
                    ("6", "Sunday"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
