# Generated by Django 4.2.13 on 2024-06-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_vendor_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="rank",
            field=models.PositiveSmallIntegerField(default="99"),
        ),
    ]
