# Generated by Django 4.2.13 on 2024-11-26 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0003_alter_vendor_rank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ["rank", "name"]},
        ),
    ]
