# Generated by Django 4.2.6 on 2023-10-16 20:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("company", models.CharField(blank=True, max_length=128, null=True)),
                ("phone_number", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NON_SHAREHOLDER", "Non-shareholder"),
                            ("SHAREHOLDER", "Shareholder"),
                            ("SHAREHOLDER_RESALE", "Shareholder Resale"),
                            ("EMPLOYEE", "Employee"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "ordering_method",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=128)),
                (
                    "product_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "book_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INCOMPLETE", "Incomplete"),
                            ("PENDING", "Pending"),
                            ("READY_TO_ORDER", "Ready to order"),
                            ("ORDERED", "Ordered"),
                            ("RECEIVED", "Received"),
                            ("CALLED", "Called"),
                            ("PICKED_UP", "Picked-Up"),
                            ("CANCELED", "Canceled"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_ordered", models.DateField(blank=True, null=True)),
                ("date_received", models.DateField(blank=True, null=True)),
                ("date_called", models.DateField(blank=True, null=True)),
                ("date_picked_up", models.DateField(blank=True, null=True)),
                ("paid", models.BooleanField(default=False)),
                ("employee_initials", models.TextField(max_length="5")),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.customer",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.vendor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="orders.customerstatus"
            ),
        ),
    ]
