# Generated by Django 4.2.6 on 2023-10-16 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_auto_20231016_1608"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerstatus",
            options={"verbose_name_plural": "contract statuses"},
        ),
    ]
