# Generated by Django 4.2.13 on 2025-03-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
    ]
