# Generated by Django 4.2.6 on 2023-10-16 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_customerstatus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerstatus",
            options={"verbose_name_plural": "customer statuses"},
        ),
    ]
