# Generated by Django 4.2.6 on 2023-10-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_customerstatus_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="memo",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="employee_initials",
            field=models.CharField(max_length=5),
        ),
    ]
