# Generated by Django 4.2.6 on 2023-10-16 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_memo_alter_order_employee_initials"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="has_bottle_deposit",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_stand_by",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="number_bottle_deposit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
