# Generated by Django 4.2.6 on 2023-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_has_bottle_deposit_order_is_stand_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="delivery_day",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="order_day",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="has_bottle_deposit",
            field=models.BooleanField(default=False),
        ),
    ]
